version: "3"
services:
  db:
    image: postgres:alpine
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret

volumes:
  db:
